name: cine_remote
description: Camera Remote Control App

# Prevents the package from being published to pub.dev
publish_to: "none"

# Version number followed by build number separated by a +.
version: 0.3.3+7

environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera_control_dart:
    path: ../camera_control_dart/
    #git:
    #  url: https://github.com/JulianSchroden/camera_control_dart.git
    #  ref: v0.0.2

  hive: ^2.2.3
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.2.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  carousel_slider: ^5.0.0
  network_info_plus: ^6.1.3
  logging: ^1.2.0
  logger: ^2.3.0
  rxdart: ^0.28.0
  path_provider: ^2.1.3
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: 2.4.14
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dummy_live_view_image.jpg
    - assets/images/canon_r7.png
    - assets/images/canon_70d.png
    - assets/images/canon_c100_ii.png
