name: cine_remote
description: Camera Remote Control App

# Prevents the package from being published to pub.dev
publish_to: "none"

# Version number followed by build number separated by a +.
version: 0.3.3+7

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera_control_dart:
    path: ../camera_control_dart/
    #git:
    #  url: https://github.com/JulianSchroden/camera_control_dart.git
    #  ref: v0.0.2

  hive: ^2.2.3
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  network_info_plus: ^5.0.3
  logging: ^1.2.0
  logger: ^2.3.0
  rxdart: ^0.28.0
  path_provider: ^2.1.3
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  meta: ^1.12.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/dummy_live_view_image.jpg
    - assets/images/canon_70d.png
    - assets/images/canon_c100_ii.png
