name: cine_remote
description: Camera Remote Control App

# Prevents the package from being published to pub.dev
publish_to: "none"

# Version number followed by build number separated by a +.
version: 0.2.0+2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  http: ^0.13.5
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  network_info_plus: ^3.0.3
  logging: ^1.1.1
  logger: ^1.3.0
  rxdart: ^0.27.7
  xml: ^6.2.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  build_runner: 2.3.0
  freezed: 2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  meta: ^1.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/dummy_live_view_image.jpg
    - assets/images/canon_70d.png
    - assets/images/canon_c100_ii.png
